In [1]:
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
import os
import matplotlib.pyplot as plt
import numpy as np
os.environ["CUDA_VISIBLE_DEVICES"]="-1"                              # CPU 설정
# os.environ["CUDA_VISIBLE_DEVICES"]="0"                               # GPU 설정


In [2]:
def f(x):
    y = x+5
    return y

In [3]:
X = np.array([k for k in range(-1000, 1000)])                      # define x
y = np.array([f(x) for x in X])                                                    # define y

In [4]:
print(X[:10])
print(y[:10])

[-1000  -999  -998  -997  -996  -995  -994  -993  -992  -991]
[-995 -994 -993 -992 -991 -990 -989 -988 -987 -986]


In [5]:
def gen_model():
    input_ = Input(shape=(1,))
    hidden = Dense(4, activation='relu')(input_)
    output = Dense(1, activation='linear')(hidden)
    
    
    
    model = Model(input_, output)
    model.compile(loss='mse', optimizer='adam')
    
    return model

In [6]:
# 단순 예제로 validation dataset을 구성하지 않음.

model = gen_model()
model.fit(X, y, batch_size=64, epochs=30)

Train on 2000 samples
Epoch 1/30
2000/2000 [==============================] - 0s 124us/sample - loss: 300488.8525
Epoch 2/30
2000/2000 [==============================] - 0s 21us/sample - loss: 262615.7037
Epoch 3/30
2000/2000 [==============================] - 0s 24us/sample - loss: 229033.9390
Epoch 4/30
2000/2000 [==============================] - 0s 16us/sample - loss: 198589.8474
Epoch 5/30
2000/2000 [==============================] - 0s 18us/sample - loss: 170756.3146
Epoch 6/30
2000/2000 [==============================] - 0s 18us/sample - loss: 145144.6471
Epoch 7/30
2000/2000 [==============================] - 0s 18us/sample - loss: 121612.4539
Epoch 8/30
2000/2000 [==============================] - 0s 22us/sample - loss: 99818.6106
Epoch 9/30
2000/2000 [==============================] - 0s 25us/sample - loss: 80008.3842
Epoch 10/30
2000/2000 [==============================] - 0s 19us/sample - loss: 62420.5474
Epoch 11/30
2000/2000 [==============================] - 0s 19us/samp

In [7]:
model.predict([2000])

array([[2012.2667]], dtype=float32)